/**
 * Kapikol Protocol Frontend Integration SDK
 * 
 * This SDK provides a comprehensive interface for integrating the Kapikol Protocol
 * smart contracts with frontend applications. It includes gas-optimized operations,
 * error handling, and real-time updates.
 */

import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, Connection, Keypair, Transaction, SystemProgram } from "@solana/web3.js";
import { TOKEN_PROGRAM_ID } from "@solana/spl-token";
import { BN } from "bn.js";

// Import the generated IDL types (these would be generated by Anchor)
interface KapikolProtocol {
  // This would be populated by the generated IDL
}

export class KapikolSDK {
  public program: Program<KapikolProtocol>;
  public connection: Connection;
  public provider: anchor.AnchorProvider;
  
  // Configuration for different environments
  public config: {
    epochDuration: number;
    minStakeAmount: number;
    maxStakeAmount: number;
    stakingFee: number;
    unstakingFeePre: number;
    unstakingFeePost: number;
    verificationPeriod: number;
    vestingDuration: number;
  };

  constructor(
    connection: Connection,
    wallet: anchor.Wallet,
    programId: PublicKey,
    config?: Partial<typeof KapikolSDK.prototype.config>
  ) {
    this.connection = connection;
    this.provider = new anchor.AnchorProvider(
      connection,
      wallet,
      { commitment: "confirmed" }
    );
    
    // Set the provider globally for Anchor
    anchor.setProvider(this.provider);

    // Initialize the program (IDL would be imported in real implementation)
    this.program = new Program({} as any, programId, this.provider);
    
    // Set default configuration based on environment
    this.config = {
      epochDuration: this.isLocalnet() ? 120 : this.isDevnet() ? 3600 : 1209600, // 2min/1hr/2weeks
      minStakeAmount: 0.1 * anchor.web3.LAMPORTS_PER_SOL,
      maxStakeAmount: 100 * anchor.web3.LAMPORTS_PER_SOL,
      stakingFee: 100, // 1% in basis points
      unstakingFeePre: 100, // 1%
      unstakingFeePost: 200, // 2%
      verificationPeriod: this.isLocalnet() ? 300 : this.isDevnet() ? 86400 : 7776000, // 5min/1day/3months
      vestingDuration: this.isLocalnet() ? 600 : this.isDevnet() ? 604800 : 94608000, // 10min/1week/3years
      ...config,
    };
  }

  // Environment detection helpers
  private isLocalnet(): boolean {
    return this.connection.rpcEndpoint.includes('localhost') || 
           this.connection.rpcEndpoint.includes('127.0.0.1');
  }

  private isDevnet(): boolean {
    return this.connection.rpcEndpoint.includes('devnet');
  }

  // PDA derivation utilities
  public async getGlobalStatePDA(): Promise<[PublicKey, number]> {
    return PublicKey.findProgramAddressSync(
      [Buffer.from("protocol")],
      this.program.programId
    );
  }

  public async getInfluencerVaultPDA(influencerId: Uint8Array): Promise<[PublicKey, number]> {
    return PublicKey.findProgramAddressSync(
      [Buffer.from("influencer_vault"), Buffer.from(influencerId)],
      this.program.programId
    );
  }

  public async getStakePositionPDA(
    staker: PublicKey,
    influencerVault: PublicKey
  ): Promise<[PublicKey, number]> {
    return PublicKey.findProgramAddressSync(
      [
        Buffer.from("stake_position"),
        staker.toBuffer(),
        influencerVault.toBuffer()
      ],
      this.program.programId
    );
  }

  public async getVestingSchedulePDA(
    beneficiary: PublicKey,
    influencerVault: PublicKey
  ): Promise<[PublicKey, number]> {
    return PublicKey.findProgramAddressSync(
      [
        Buffer.from("vesting_schedule"),
        beneficiary.toBuffer(),
        influencerVault.toBuffer()
      ],
      this.program.programId
    );
  }

  // Core protocol operations

  /**
   * Initialize the protocol with configurable parameters
   */
  public async initializeProtocol(
    authority: Keypair,
    treasuryAuthority: PublicKey,
    upgradeAuthority: PublicKey,
    config?: Partial<typeof this.config>
  ): Promise<string> {
    const [globalStatePDA] = await this.getGlobalStatePDA();
    const [platformTreasuryPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("platform_treasury")],
      this.program.programId
    );
    const [sheisDAOTreasuryPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("sheis_dao_treasury")],
      this.program.programId
    );
    const [developerVestingPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("developer_vesting")],
      this.program.programId
    );

    const protocolConfig = {
      epochDuration: new BN(config?.epochDuration || this.config.epochDuration),
      minStakeAmount: new BN(config?.minStakeAmount || this.config.minStakeAmount),
      maxStakeAmount: new BN(config?.maxStakeAmount || this.config.maxStakeAmount),
      minLaunchScore: new BN(1 * anchor.web3.LAMPORTS_PER_SOL),
      stakingFee: config?.stakingFee || this.config.stakingFee,
      unstakingFeePre: config?.unstakingFeePre || this.config.unstakingFeePre,
      unstakingFeePost: config?.unstakingFeePost || this.config.unstakingFeePost,
      verificationPeriod: new BN(config?.verificationPeriod || this.config.verificationPeriod),
      vestingDuration: new BN(config?.vestingDuration || this.config.vestingDuration),
    };

    try {
      const tx = await this.program.methods
        .initializeProtocol(protocolConfig)
        .accounts({
          globalState: globalStatePDA,
          platformTreasury: platformTreasuryPDA,
          sheisDAOTreasury: sheisDAOTreasuryPDA,
          developerVesting: developerVestingPDA,
          authority: authority.publicKey,
          treasuryAuthority,
          upgradeAuthority,
          systemProgram: SystemProgram.programId,
          tokenProgram: TOKEN_PROGRAM_ID,
          rent: anchor.web3.SYSVAR_RENT_PUBKEY,
        })
        .signers([authority])
        .rpc();

      console.log("✅ Protocol initialized successfully");
      console.log(`   - Transaction: ${tx}`);
      console.log(`   - Epoch duration: ${protocolConfig.epochDuration.toNumber()}s`);
      console.log(`   - Environment: ${this.getEnvironmentName()}`);

      return tx;
    } catch (error) {
      console.error("❌ Protocol initialization failed:", error);
      throw new Error(`Failed to initialize protocol: ${error.message}`);
    }
  }

  /**
   * Create an influencer vault
   */
  public async createInfluencerVault(
    creator: Keypair,
    socialHandle: string
  ): Promise<{ txId: string; influencerVault: PublicKey; influencerId: Uint8Array }> {
    // Generate a unique influencer ID
    const influencerId = new Uint8Array(await crypto.subtle.digest(
      'SHA-256',
      new TextEncoder().encode(socialHandle + Date.now())
    ));

    const [globalStatePDA] = await this.getGlobalStatePDA();
    const [influencerVaultPDA] = await this.getInfluencerVaultPDA(influencerId);

    try {
      const tx = await this.program.methods
        .createInfluencerVault(Array.from(influencerId), socialHandle)
        .accounts({
          globalState: globalStatePDA,
          influencerVault: influencerVaultPDA,
          creator: creator.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([creator])
        .rpc();

      console.log(`✅ Influencer vault created for ${socialHandle}`);
      console.log(`   - Transaction: ${tx}`);
      console.log(`   - Vault PDA: ${influencerVaultPDA.toString()}`);

      return {
        txId: tx,
        influencerVault: influencerVaultPDA,
        influencerId,
      };
    } catch (error) {
      console.error("❌ Failed to create influencer vault:", error);
      throw new Error(`Failed to create influencer vault: ${error.message}`);
    }
  }

  /**
   * Stake on an influencer with gas optimization
   */
  public async stakeOnInfluencer(
    staker: Keypair,
    influencerVault: PublicKey,
    amountSOL: number
  ): Promise<{ txId: string; netAmount: number; fee: number }> {
    const amountLamports = Math.floor(amountSOL * anchor.web3.LAMPORTS_PER_SOL);
    
    // Validate amount
    if (amountLamports < this.config.minStakeAmount) {
      throw new Error(`Minimum stake amount is ${this.config.minStakeAmount / anchor.web3.LAMPORTS_PER_SOL} SOL`);
    }
    if (amountLamports > this.config.maxStakeAmount) {
      throw new Error(`Maximum stake amount is ${this.config.maxStakeAmount / anchor.web3.LAMPORTS_PER_SOL} SOL`);
    }

    const [globalStatePDA] = await this.getGlobalStatePDA();
    const [stakePositionPDA] = await this.getStakePositionPDA(staker.publicKey, influencerVault);
    const [platformTreasuryPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("platform_treasury")],
      this.program.programId
    );

    // Calculate expected fee for display
    const expectedFee = Math.floor(amountLamports * this.config.stakingFee / 10000);
    const expectedNetAmount = amountLamports - expectedFee;

    try {
      const tx = await this.program.methods
        .stakeOnInfluencer(new BN(amountLamports))
        .accounts({
          globalState: globalStatePDA,
          influencerVault: influencerVault,
          stakePosition: stakePositionPDA,
          platformTreasury: platformTreasuryPDA,
          staker: staker.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([staker])
        .rpc();

      console.log(`✅ Staking successful: ${amountSOL} SOL`);
      console.log(`   - Transaction: ${tx}`);
      console.log(`   - Net amount: ${expectedNetAmount / anchor.web3.LAMPORTS_PER_SOL} SOL`);
      console.log(`   - Platform fee: ${expectedFee / anchor.web3.LAMPORTS_PER_SOL} SOL`);

      return {
        txId: tx,
        netAmount: expectedNetAmount / anchor.web3.LAMPORTS_PER_SOL,
        fee: expectedFee / anchor.web3.LAMPORTS_PER_SOL,
      };
    } catch (error) {
      console.error("❌ Staking failed:", error);
      throw new Error(`Failed to stake: ${error.message}`);
    }
  }

  /**
   * Unstake before token launch (1% fee)
   */
  public async unstakePreLaunch(
    staker: Keypair,
    influencerVault: PublicKey
  ): Promise<{ txId: string; returnAmount: number; fee: number }> {
    const [globalStatePDA] = await this.getGlobalStatePDA();
    const [stakePositionPDA] = await this.getStakePositionPDA(staker.publicKey, influencerVault);
    const [platformTreasuryPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("platform_treasury")],
      this.program.programId
    );

    try {
      // Get current stake position to calculate expected return
      const stakePosition = await this.program.account.stakePosition.fetch(stakePositionPDA);
      const netAmount = stakePosition.netAmount.toNumber();
      const expectedFee = Math.floor(netAmount * this.config.unstakingFeePre / 10000);
      const expectedReturn = netAmount - expectedFee;

      const tx = await this.program.methods
        .unstakePreLaunch()
        .accounts({
          globalState: globalStatePDA,
          influencerVault: influencerVault,
          stakePosition: stakePositionPDA,
          platformTreasury: platformTreasuryPDA,
          staker: staker.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([staker])
        .rpc();

      console.log("✅ Pre-launch unstaking successful");
      console.log(`   - Transaction: ${tx}`);
      console.log(`   - Return amount: ${expectedReturn / anchor.web3.LAMPORTS_PER_SOL} SOL`);
      console.log(`   - Unstaking fee: ${expectedFee / anchor.web3.LAMPORTS_PER_SOL} SOL`);

      return {
        txId: tx,
        returnAmount: expectedReturn / anchor.web3.LAMPORTS_PER_SOL,
        fee: expectedFee / anchor.web3.LAMPORTS_PER_SOL,
      };
    } catch (error) {
      console.error("❌ Unstaking failed:", error);
      throw new Error(`Failed to unstake: ${error.message}`);
    }
  }

  // Query methods for frontend display

  /**
   * Get global protocol state
   */
  public async getGlobalState(): Promise<any> {
    const [globalStatePDA] = await this.getGlobalStatePDA();
    try {
      return await this.program.account.globalProtocolState.fetch(globalStatePDA);
    } catch (error) {
      console.log("Protocol not yet initialized");
      return null;
    }
  }

  /**
   * Get influencer vault information
   */
  public async getInfluencerVault(influencerVault: PublicKey): Promise<any> {
    try {
      return await this.program.account.influencerVault.fetch(influencerVault);
    } catch (error) {
      console.error("Failed to fetch influencer vault:", error);
      return null;
    }
  }

  /**
   * Get user's stake position
   */
  public async getStakePosition(staker: PublicKey, influencerVault: PublicKey): Promise<any> {
    const [stakePositionPDA] = await this.getStakePositionPDA(staker, influencerVault);
    try {
      return await this.program.account.stakePosition.fetch(stakePositionPDA);
    } catch (error) {
      console.log("No stake position found");
      return null;
    }
  }

  /**
   * Get all influencer vaults (paginated)
   */
  public async getAllInfluencerVaults(limit: number = 50, offset: number = 0): Promise<any[]> {
    try {
      const vaults = await this.program.account.influencerVault.all();
      return vaults.slice(offset, offset + limit);
    } catch (error) {
      console.error("Failed to fetch influencer vaults:", error);
      return [];
    }
  }

  /**
   * Get user's all stake positions
   */
  public async getUserStakePositions(staker: PublicKey): Promise<any[]> {
    try {
      const positions = await this.program.account.stakePosition.all([
        {
          memcmp: {
            offset: 8, // Skip discriminator
            bytes: staker.toBase58(),
          },
        },
      ]);
      return positions;
    } catch (error) {
      console.error("Failed to fetch stake positions:", error);
      return [];
    }
  }

  // Utility methods

  /**
   * Check if current epoch is complete
   */
  public async isEpochComplete(): Promise<boolean> {
    const globalState = await this.getGlobalState();
    if (!globalState) return false;

    const currentTime = Math.floor(Date.now() / 1000);
    const epochEndTime = globalState.epochStartTime.toNumber() + globalState.epochDuration.toNumber();
    
    return currentTime >= epochEndTime;
  }

  /**
   * Get time remaining in current epoch
   */
  public async getEpochTimeRemaining(): Promise<number> {
    const globalState = await this.getGlobalState();
    if (!globalState) return 0;

    const currentTime = Math.floor(Date.now() / 1000);
    const epochEndTime = globalState.epochStartTime.toNumber() + globalState.epochDuration.toNumber();
    
    return Math.max(0, epochEndTime - currentTime);
  }

  /**
   * Get environment name for display
   */
  public getEnvironmentName(): string {
    if (this.isLocalnet()) return "Local Testnet";
    if (this.isDevnet()) return "DevNet";
    return "MainNet";
  }

  /**
   * Calculate expected token allocation for a stake
   */
  public calculateExpectedTokens(
    userStakeAmount: number,
    totalStaked: number,
    tokenAllocation: number = 300_000_000 // 30% of 1B tokens
  ): number {
    if (totalStaked === 0) return 0;
    return (userStakeAmount / totalStaked) * tokenAllocation;
  }

  /**
   * Format SOL amount for display
   */
  public static formatSOL(lamports: number): string {
    return `${(lamports / anchor.web3.LAMPORTS_PER_SOL).toFixed(4)} SOL`;
  }

  /**
   * Format large numbers with abbreviations
   */
  public static formatNumber(num: number): string {
    if (num >= 1e9) return (num / 1e9).toFixed(2) + 'B';
    if (num >= 1e6) return (num / 1e6).toFixed(2) + 'M';
    if (num >= 1e3) return (num / 1e3).toFixed(2) + 'K';
    return num.toString();
  }

  // Event listener for real-time updates
  public subscribeToInfluencerVaultUpdates(
    influencerVault: PublicKey,
    callback: (vault: any) => void
  ): number {
    return this.program.account.influencerVault.subscribe(
      influencerVault,
      "confirmed"
    ).addListener("change", callback);
  }

  public unsubscribe(subscriptionId: number): void {
    this.program.account.influencerVault.unsubscribe(subscriptionId);
  }
}